name: groc
root: .

windows:
  - dev:
      layout: even-horizontal
      panes:
        -
        - pnpm run dev:all
  - tests:
      layout: even-horizontal
      panes:
        - pnpm run test:unit
        - pnpm run test:e2e
