name: groc
root: .

windows:
  - dev:
      layout: even-horizontal
      panes:
        -
        - bun run dev:all
  - tests:
      layout: even-horizontal
      panes:
        - bun run test:unit --watch
        - bun run test:e2e
