name: '🌐 Translation Request'
description: Request a translation for content
title: "🌐 TRANSLATION: "
labels: ["type: translation", "status: waiting", "priority: low"]
body:
- type: textarea
  attributes:
    label: Content to Translate
    description: Provide details about the content you'd like to have translated.
  validations:
    required: true
- type: input
  id: language
  attributes:
    label: Target Language
    description: Specify the target language for the translation.
    placeholder: "E.g., Spanish, French, German"
  validations:
    required: true
